-- ===========================================
-- 0. PROFILES – bez avatar_id (přidáme až pak)
-- ===========================================
CREATE TABLE profiles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          is_verified BOOLEAN NOT NULL DEFAULT false,
                          two_factor_email BOOLEAN NOT NULL DEFAULT FALSE,
                          verification_code VARCHAR(100),
                          verification_code_expiration TIMESTAMP,
                          created_at TIMESTAMP NOT NULL DEFAULT now(),
                          updated_at TIMESTAMP NOT NULL DEFAULT now(),
                          avatar_id BIGINT
);

-- ===========================================
-- 1. USERS – Odkazují na `profiles`
-- ===========================================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(20) NOT NULL DEFAULT 'USER',
                       phone_number VARCHAR(15) NOT NULL,
                       date_of_birth DATE NOT NULL,
                       profile_id BIGINT NOT NULL UNIQUE,
                       CONSTRAINT fk_users_profile
                           FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);

-- ===========================================
-- 2. ARTISTS – Odkazují na `profiles`
-- ===========================================
CREATE TABLE artists (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         email VARCHAR(255) NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         role VARCHAR(20) NOT NULL DEFAULT 'ARTIST',
                         phone_number VARCHAR(15) NOT NULL,
                         date_of_birth DATE NOT NULL,
                         profile_id BIGINT NOT NULL UNIQUE,
                         plays BIGINT NOT NULL DEFAULT 0,
                         num_of_songs BIGINT NOT NULL DEFAULT 0,
                         CONSTRAINT fk_artists_profile
                             FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

ALTER TABLE artists ADD CONSTRAINT artists_email_key UNIQUE (email);

-- ===========================================
-- 3. AVATARS – Navázány na `profiles`
-- ===========================================
CREATE TABLE avatars (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         image_url TEXT NOT NULL,
                         public_id TEXT NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT now(),
                         profile_id BIGINT NOT NULL,
                         CONSTRAINT fk_avatars_profile
                             FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_avatars_profile_id ON avatars(profile_id);

-- ===========================================
-- 4. DODATEK – přidání avatar_id do `profiles` až po vytvoření `avatars`
-- ===========================================

ALTER TABLE profiles
    ADD CONSTRAINT fk_profiles_avatar
        FOREIGN KEY (avatar_id) REFERENCES avatars(id) ON DELETE SET NULL;
