-- ===========================================
-- 4. SONGS – Písničky umělců
-- ===========================================
CREATE TABLE songs (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       duration INT NOT NULL,
                       release_date DATE NOT NULL,
                       genre VARCHAR(100),
                       plays BIGINT NOT NULL DEFAULT 0,
                       artist_id BIGINT NOT NULL,
                       type VARCHAR(20) NOT NULL DEFAULT 'SINGLE',
                       song_image_id BIGINT,
                       CONSTRAINT fk_songs_artist
                           FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
);

-- ===========================================
-- 5. SONG_IMAGES – Obrázky pro písničky
-- ===========================================
CREATE TABLE song_images (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             image_url TEXT NOT NULL,
                             public_id TEXT NOT NULL,
                             ord INT NOT NULL,
                             type VARCHAR(50) NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT now(),
                             song_id BIGINT NOT NULL,
                             CONSTRAINT fk_song_images_song
                                 FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
);

-- Foreign key z songs na song_images
ALTER TABLE songs ADD CONSTRAINT fk_songs_image
    FOREIGN KEY (song_image_id) REFERENCES song_images(id) ON DELETE SET NULL;

-- ===========================================
-- 6. INDEXY pro rychlost
-- ===========================================
CREATE INDEX idx_songs_artist_id ON songs(artist_id);
CREATE INDEX idx_song_images_song_id ON song_images(song_id);